// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WardMate.Services.ApplicationWorkflow.Infrastructure;

#nullable disable

namespace WardMate.Services.ApplicationWorkflow.Infrastructure.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20261009095949_WardScopedFinalDecisions")]
    partial class WardScopedFinalDecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("application_code_sequence");

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_application_checklists");

                    b.HasIndex("ApplicationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_application_checklists_application_id_code");

                    b.ToTable("application_checklists", null, t =>
                        {
                            t.HasCheckConstraint("ck_checklists_status", "status IN ('PENDING','COMPLETED','REJECTED')");
                        });
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ApplicationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_version_id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field_label");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("officer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_application_comments");

                    b.HasIndex("ApplicationId", "ApplicationVersionId", "Status")
                        .HasDatabaseName("ix_application_comments_application_id_application_version_id_");

                    b.ToTable("application_comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_comments_status", "status IN ('OPEN','RESOLVED')");

                            t.HasCheckConstraint("ck_application_comments_target", "target_type IN ('FORM_FIELD','CHECKLIST_ITEM')");
                        });
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_code");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("AssignedOfficerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_officer_id");

                    b.Property<string>("CaseCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.Property<string>("ProcedureTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("procedure_title");

                    b.Property<int>("ResubmitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resubmit_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ward_code");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("ApplicationCode")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_application_code");

                    b.HasIndex("AssignedOfficerId")
                        .HasDatabaseName("ix_applications_assigned_officer_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_applications_user_id_created_at");

                    b.HasIndex("Status", "SubmittedAt", "Id")
                        .HasDatabaseName("ix_applications_status_submitted_at_id");

                    b.HasIndex("WardCode", "Status", "SubmittedAt")
                        .HasDatabaseName("ix_applications_ward_code_status_submitted_at");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_applications_status", "status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','NEED_REVISION','APPROVED','CANCELLED','REJECTED')");
                        });
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_application_status_history");

                    b.HasIndex("ApplicationId", "CreatedAt")
                        .HasDatabaseName("ix_application_status_history_application_id_created_at");

                    b.ToTable("application_status_history", (string)null);
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_application_versions");

                    b.HasAlternateKey("ApplicationId", "Id")
                        .HasName("ak_application_versions_application_id_id");

                    b.HasIndex("ApplicationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_application_versions_application_id_version_number");

                    b.ToTable("application_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_versions_number", "version_number > 0");
                        });
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationChecklist", b =>
                {
                    b.HasOne("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", null)
                        .WithMany("Checklists")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_checklists_applications_application_id");
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationComment", b =>
                {
                    b.HasOne("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", null)
                        .WithMany("Comments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_comments_applications_application_id");

                    b.HasOne("WardMate.Services.ApplicationWorkflow.Domain.ApplicationVersion", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "ApplicationVersionId")
                        .HasPrincipalKey("ApplicationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_comments_application_versions_application_id_ap");
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationStatusHistory", b =>
                {
                    b.HasOne("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", null)
                        .WithMany("History")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_status_history_applications_application_id");
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationVersion", b =>
                {
                    b.HasOne("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", null)
                        .WithMany("Versions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_versions_applications_application_id");
                });

            modelBuilder.Entity("WardMate.Services.ApplicationWorkflow.Domain.ApplicationRecord", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Comments");

                    b.Navigation("History");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
