// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WardMate.Services.ProcedureCatalog.Infrastructure.Persistence;

#nullable disable

namespace WardMate.Services.ProcedureCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcedureDbContext))]
    [Migration("20261001070638_ProcedureOriginalPdf")]
    partial class ProcedureOriginalPdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ChecklistSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("checklist_schema");

                    b.Property<string>("ContentPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_payload");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExecutingAgency")
                        .HasColumnType("text")
                        .HasColumnName("executing_agency");

                    b.Property<string>("FeeSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("Miễn phí")
                        .HasColumnName("fee_summary");

                    b.Property<string>("FormDefinitions")
                        .HasColumnType("jsonb")
                        .HasColumnName("form_definitions");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("LevelOfImplementation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Cấp Xã")
                        .HasColumnName("level_of_implementation");

                    b.Property<string>("OriginalPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_pdf_url");

                    b.Property<string>("PdfFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pdf_file_name");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("procedure_code");

                    b.Property<string>("ProcessingTimeSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("1 ngày")
                        .HasColumnName("processing_time_summary");

                    b.Property<string>("StatusChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("status_change_reason");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("Công dân Việt Nam")
                        .HasColumnName("target_audience");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_procedures");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_procedures_category_id");

                    b.HasIndex("ChecklistSchema")
                        .HasDatabaseName("ix_procedures_checklist_schema");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ChecklistSchema"), "gin");

                    b.HasIndex("ContentPayload")
                        .HasDatabaseName("ix_procedures_content_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContentPayload"), "gin");

                    b.HasIndex("ProcedureCode")
                        .IsUnique()
                        .HasDatabaseName("ix_procedures_procedure_code");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProcedureCode"), "btree");

                    b.ToTable("procedures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("07000000-0000-0000-0000-000000000001"),
                            CategoryId = 1,
                            ChecklistSchema = "[{\"checklistId\":\"TO_KHAI\",\"caseCode\":\"THONG_THUONG\",\"submissionType\":\"NOP\",\"itemName\":\"T\\u1EDD khai \\u0111\\u0103ng k\\u00FD k\\u1EBFt h\\u00F4n (m\\u1EABu)\",\"documentCopyType\":\"ORIGINAL\",\"quantity\":1,\"conditionNote\":null,\"isMandatory\":true},{\"checklistId\":\"DINH_DANH\",\"caseCode\":null,\"submissionType\":\"XUAT_TRINH\",\"itemName\":\"Gi\\u1EA5y t\\u1EDD \\u0111\\u1ECBnh danh (m\\u1EABu)\",\"documentCopyType\":\"ORIGINAL\",\"quantity\":1,\"conditionNote\":\"\\u0110\\u1ED1i chi\\u1EBFu th\\u00F4ng tin minh h\\u1ECDa\",\"isMandatory\":true}]",
                            ContentPayload = "{\"decisionNumber\":\"DEMO-QD-01\",\"receivingAddress\":\"B\\u1ED9 ph\\u1EADn ti\\u1EBFp nh\\u1EADn v\\u00E0 tr\\u1EA3 k\\u1EBFt qu\\u1EA3 (minh h\\u1ECDa)\",\"submissionMethods\":[{\"methodName\":\"Tr\\u1EF1c ti\\u1EBFp\",\"feeAmount\":0,\"feeUnit\":\"VND\",\"estimatedDays\":1,\"note\":\"D\\u1EEF li\\u1EC7u th\\u1EED nghi\\u1EC7m \\u00E1nh x\\u1EA1 JSONB\"}],\"legalReferences\":[{\"documentNumber\":\"DEMO-VB-01\",\"documentName\":\"V\\u0103n b\\u1EA3n minh h\\u1ECDa, kh\\u00F4ng d\\u00F9ng l\\u00E0m c\\u0103n c\\u1EE9 ph\\u00E1p l\\u00FD\",\"issueDate\":\"2026-09-01\",\"authority\":\"C\\u01A1 quan minh h\\u1ECDa\"}],\"results\":[\"Gi\\u1EA5y ch\\u1EE9ng nh\\u1EADn k\\u1EBFt h\\u00F4n (minh h\\u1ECDa)\"],\"cases\":[{\"caseCode\":\"THONG_THUONG\",\"caseName\":\"Tr\\u01B0\\u1EDDng h\\u1EE3p th\\u00F4ng th\\u01B0\\u1EDDng (minh h\\u1ECDa)\",\"steps\":[{\"stepOrder\":1,\"stepName\":\"Ti\\u1EBFp nh\\u1EADn\",\"executor\":\"C\\u00E1n b\\u1ED9 ti\\u1EBFp nh\\u1EADn\",\"actionDetails\":\"Ki\\u1EC3m tra th\\u00E0nh ph\\u1EA7n h\\u1ED3 s\\u01A1 m\\u1EABu\"},{\"stepOrder\":2,\"stepName\":\"Tr\\u1EA3 k\\u1EBFt qu\\u1EA3\",\"executor\":\"C\\u00E1n b\\u1ED9 h\\u1ED9 t\\u1ECBch\",\"actionDetails\":\"Tr\\u1EA3 k\\u1EBFt qu\\u1EA3 theo quy tr\\u00ECnh minh h\\u1ECDa\"}]}]}",
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExecutingAgency = "Ủy ban nhân dân cấp xã",
                            FeeSummary = "Miễn phí",
                            FormDefinitions = "[{\"formTemplateId\":null,\"caseCode\":\"THONG_THUONG\",\"formCode\":\"DEMO-TK-01\",\"formName\":\"T\\u1EDD khai \\u0111i\\u1EC7n t\\u1EED minh h\\u1ECDa\",\"formType\":\"ONLINE_INTERACTIVE\",\"quantity\":1,\"isMandatory\":true},{\"formTemplateId\":null,\"caseCode\":null,\"formCode\":\"DEMO-DOCX-01\",\"formName\":\"M\\u1EABu DOCX minh h\\u1ECDa\",\"formType\":\"DOCX_TEMPLATE\",\"quantity\":1,\"isMandatory\":false}]",
                            IsActive = true,
                            IssuingAuthority = "Cơ quan ban hành minh họa",
                            LevelOfImplementation = "Cấp Xã",
                            ProcedureCode = "DEMO-KET-HON",
                            ProcessingTimeSummary = "1 ngày",
                            TargetAudience = "Công dân Việt Nam",
                            Title = "Đăng ký kết hôn (dữ liệu minh họa)",
                            UpdatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.ProcedureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_procedure_categories");

                    b.ToTable("procedure_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Hộ tịch",
                            Description = "Các thủ tục hộ tịch"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Đất đai",
                            Description = "Các thủ tục đất đai"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Quản lý công sản",
                            Description = "Các thủ tục quản lý công sản"
                        });
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.ProcedureVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DecisionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decision_number");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("OriginalPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_pdf_url");

                    b.Property<string>("PdfFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pdf_file_name");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_procedure_versions");

                    b.HasIndex("ProcedureId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_procedure_versions_procedure_id_version_number");

                    b.ToTable("procedure_versions", (string)null);
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.Procedure", b =>
                {
                    b.HasOne("WardMate.Services.ProcedureCatalog.Domain.Entities.ProcedureCategory", "Category")
                        .WithMany("Procedures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedures_procedure_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.ProcedureVersion", b =>
                {
                    b.HasOne("WardMate.Services.ProcedureCatalog.Domain.Entities.Procedure", "Procedure")
                        .WithMany("Versions")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedure_versions_procedures_procedure_id");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.Procedure", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WardMate.Services.ProcedureCatalog.Domain.Entities.ProcedureCategory", b =>
                {
                    b.Navigation("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
