<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup><PackageReference Include="PdfPig" Version="0.1.16" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../WardMate.Services.AIOCR.Application/WardMate.Services.AIOCR.Application.csproj" />
  </ItemGroup>
</Project>
